spring:
  config:
    import: "optional:configserver:"
  application:
    name: companies-crud
  datasource:
    username: debuggeandoideas
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://db:5432/companies
    password: udemy
